name: Build HTCondor native packages

on:
  push:
    branches: [ "main", "gha-actions-test" ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: htcondor/nmi-build:x86_64_v2_AlmaLinux10-24090101
      env:
        OMP_NUM_THREADS: 4
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 4
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Native Package Build
        run: (./build-on-linux.sh)

