name: Build HTCondor native packages

on:
  push:
    branches: [ "main", "gha-actions-test" ]
jobs:
  build:
    strategy:
      matrix:
        instance: [ 
        {"img": "ubuntu-latest", "container": "htcondor/nmi-build:x86_64_v2_AlmaLinux10-24090101"},
        {"img": "ubuntu-latest", "container": "htcondor/nmi-build:x86_64_AlmaLinux8-24090100"},
        {"img": "ubuntu-latest", "container": "htcondor/nmi-build:x86_64_AlmaLinux9-24090100"},
        {"img": "ubuntu-latest", "container": "htcondor/nmi-build:x86_64_AlmaLinux10-24090100"},
        {"img": "ubuntu-latest", "container": "htcondor/nmi-build:x86_64_AmazonLinux2023-24090100"},
        {"img": "ubuntu-latest", "container": "htcondor/nmi-build:x86_64_Debian11-24090100"},
        {"img": "ubuntu-latest", "container": "htcondor/nmi-build:x86_64_Debian12-24090100"},
        {"img": "ubuntu-latest", "container": "htcondor/nmi-build:x86_64_openSUSE15-24090100"},
        {"img": "ubuntu-latest", "container": "htcondor/nmi-build:x86_64_Ubuntu22-24090100"},
        {"img": "ubuntu-latest", "container": "htcondor/nmi-build:x86_64_Ubuntu24-24090100"},
        {"img": "ubuntu-latest", "container": "htcondor/nmi-build:x86_64_Fedora41-24090100"},
        {"img": "ubuntu-24.04-arm", "container": "htcondor/nmi-build:aarch64_AlmaLinux8-24090100"},
        {"img": "ubuntu-24.04-arm", "container": "htcondor/nmi-build:aarch64_AlmaLinux9-24090100"},
        {"img": "ubuntu-24.04-arm", "container": "htcondor/nmi-build:aarch64_AlmaLinux10-24090100"},
      ]
    # Host OS and CPU
    runs-on: ${{ matrix.instance.img }}

    # Use htcondor build containers for the real work
    container:
      image: ${{ matrix.instance.container }}
      env:
        OMP_NUM_THREADS: 4
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 4
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Native Package Build
        run: (./build-on-linux.sh .)

  macbuild:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Install dependencies
        run: brew install perl

      - name: Build
        run: (mkdir __build && cd __build && cmake -GNinja -DWITH_VOMS:bool=false .. && ninja -j4 install)

      - name: Test
        run: (cd __build && ctest -j 20 -VV)

  winbuild:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install VC++ Build Tools
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          distribution: strawberry

      - name: cmake configuration
        run: (cmake -G "Visual Studio 17 2022" -DWITH_KRB5:bool=false .)

      - name: build
        run: (cmake --build . --verbose --config Release --parallel 4)
